### ISSUE TITLE
[2022.2.24.27]打开多个实时便笺提醒后启动报错

### ISSUE THREAD

**Issue by chenshaa** [DGP-Studio/Snap.Genshin#190]
看起来应该是关于toast的问题。
```
System.InvalidOperationException: We have reached max lines allowed (4) per toast
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.AddText(String text, Nullable`1 hintStyle, Nullable`1 hintWrap, Nullable`1 hintMaxLines, Nullable`1 hintMinLines, Nullable`1 hintAlign, String language)
   at DGP.Genshin.Service.DailyNoteService.TriggerDailyNoteNotifications(UserGameRole userGameRole, DailyNote dailyNote) in D:\Develop\Projects\Snap.Genshin\DGP.Genshin\Service\DailyNoteService.cs:line 120
   at DGP.Genshin.Service.DailyNoteService.<>c__DisplayClass12_0.<UpdateDailyNotesAsync>b__0() in D:\Develop\Projects\Snap.Genshin\DGP.Genshin\Service\DailyNoteService.cs:line 80
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at DGP.Genshin.Service.DailyNoteService.UpdateDailyNotesAsync() in D:\Develop\Projects\Snap.Genshin\DGP.Genshin\Service\DailyNoteService.cs:line 80
   at DGP.Genshin.Service.DailyNoteService.Initialize() in D:\Develop\Projects\Snap.Genshin\DGP.Genshin\Service\DailyNoteService.cs:line 38
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at DGP.Genshin.App.Main()
```

**Comment by Lightczx** [comment]
删除settings.json 启动后不要勾选树脂通知下面的全部三个选项
