### ISSUE TITLE
[Bug]: 成就统计 页面导入 椰羊 的统计数据失败

### ISSUE THREAD

**Issue by TTTornado** [DGP-Studio/Snap.Genshin#257]
### Windows 版本

22000.556

### Snap Genshin 版本

4.7 build 70

### Snap Genshin 用户设备ID

92646A7E0E1E6FD5FEF1299503B7C346

### 发生了什么？

`成就统计`页面导入从`椰羊`直接导出的json文件出错，并且 椰羊-设置-本地导出-导出数据 解压后没有`成就统计.json`

### 你期望发生的行为？

成功导入成就统计数据

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by AdminRoc** [comment]
1. **cocogoat.work**在识别成就并导出时可能会缺乏相关参数，导致不能被导入。
2. **cocogoat.work** 所进行的成就导出并不属于SG内的情况，原则上不应当负责解决。
3. 另行推荐可能使用更加方便的成就导出项目：https://github.com/HolographicHat/genshin-achievement-export  
4.目前成就统计功能尚在‘尝鲜阶段’，所以暂时推荐了其他成就扫描/导出工具，但这些是sg之外的功能。请持续关注SG后续的更新，感谢支持

**Comment by TTTornado** [comment]
> 1. **cocogoat.work**在识别成就并导出时可能会缺乏相关参数，导致不能被导入。
> 2. **cocogoat.work** 所进行的成就导出并不属于SG内的情况，原则上不应当负责解决。
> 3. 另行推荐可能使用更加方便的成就导出项目：https://github.com/HolographicHat/genshin-achievement-export  
> 4.目前成就统计功能尚在‘尝鲜阶段’，所以暂时推荐了其他成就扫描/导出工具，但这些是sg之外的功能。请持续关注SG后续的更新，感谢支持

虽然可能是椰羊那边的问题，但我觉得既然做了这个功能，无法使用还是应该解决一下的，否则大可以说我们不支持，不去做这个功能😂
感谢答复w

**Comment by Lightczx** [comment]
从椰羊导入只是为了兼容早期版本的 [HolographicHat/genshin-achievement-export](https://github.com/HolographicHat/genshin-achievement-export) 的导入
后续版本将会移除这个选项

**Comment by xytoki** [comment]
椰羊已在 https://github.com/YuehaiTeam/cocogoat/commit/0d01ac232b957ffb8d4be21ab39d1f9f487409db 中调整对相关参数的处理方式以修复此问题。如需导出椰羊里的数据，请在成就页面右上角点击导出-下拉菜单-椰羊JSON。

**Comment by XeonHis** [comment]
**Snap Genshin版本** : 4.13 build86
**Device ID**: D42E8A2900B963ECA285A1DDB4876048

通过椰羊网页导出JSON报错显示**导入的数据中包含了不正确的项目**

尝试手动修改json文件为[以下格式](https://github.com/HolographicHat/genshin-achievement-export/issues/6)无果
```
[
    {
        "Id" : 80001,
        "DateTime" : "yyyy-MM-dd HH:mm:ss"
    },
    {...},
    ...
]
```

（暂未在文档页面找到成就导入的具体格式）

**Comment by xytoki** [comment]
> **Snap Genshin版本** : 4.13 build86 **Device ID**: D42E8A2900B963ECA285A1DDB4876048
> 
> 通过椰羊网页导出JSON报错显示**导入的数据中包含了不正确的项目**
> 
> 尝试手动修改json文件为[以下格式](https://github.com/HolographicHat/genshin-achievement-export/issues/6)无果
> 
> ```
> [
>     {
>         "Id" : 80001,
>         "DateTime" : "yyyy-MM-dd HH:mm:ss"
>     },
>     {...},
>     ...
> ]
> ```
> 
> （暂未在文档页面找到成就导入的具体格式）

应该还是椰羊这边的问题，可能有存量识别错误导致格式不对的数据没有完全完成迁移。
目前已知的情况有：
1. 识别的年份不正常，导致产生20211这样的错误年份，可在导出的JSON中搜索`"+`找到
2. 从压缩包里解压的导出数据含有一些多余的元数据，导致无法导入
 
可以先查一下以上两个，如果还有问题的话可以到椰羊提issue

另：SG的成就格式在 [genshin-achievement-export的代码中](https://github.com/HolographicHat/genshin-achievement-export/blob/700cbbb86dc3eb0be9d1e74100865b0889aad7a9/export.js#L33-L40) 可以找到

**Comment by Lightczx** [comment]
@xytoki 

```
            {
                "id": 81023,
                "date": "2021-06-20T16:00:00.000Z",
                "status": "手动勾选",
                "categoryId": 0
            },
            {
                "id": 81024,
                "date": "+020201-03-31T16:00:00.000Z",
                "status": "手动勾选",
                "categoryId": 0
            },
            {
                "id": 81025,
                "date": "2021-01-17T16:00:00.000Z",
                "status": "手动勾选",
                "categoryId": 0
            },
```

不是很清楚为什么能导入形如第二个date 的项

```
引发的异常:“Newtonsoft.Json.JsonReaderException”(位于 Newtonsoft.Json.dll 中)
Newtonsoft.Json.JsonReaderException: Could not convert string to DateTime: +020201-03-31T16:00:00.000Z. Path 'value.achievements[12].date', line 79, position 53.
   at Newtonsoft.Json.JsonReader.ReadDateTimeString(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsDateTime()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Snap.Data.Json.Json.ToObject[T](String value) in D:\Develop\Projects\Snap.Genshin\Common\Snap.Data.Json\Json.cs:line 23
```
```
"date": "+020201-03-31T16:00:00.000Z",
```
就是第79行，篇幅限制前后数据就忽略了
