### ISSUE TITLE
[Bug]: 祈愿记录打不开

### ISSUE THREAD

**Issue by Atheris0vv0** [DGP-Studio/Snap.Genshin#303]
### Windows 版本

19044.1706

### Snap Genshin 版本

2022.2.1

### Snap Genshin 用户设备ID

8D046797FE43E6A0842BF3D240174555

### 发生了什么？

试图打开抽卡记录就会报错，之前是更新抽卡记录到第一页突然报错，后来干脆没法打开抽卡记录了

### 你期望发生的行为？

能正常打开并更新祈愿记录

### 相关的崩溃日志

```shell
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at DGP.Genshin.Service.GachaStatistic.StatisticBuilder.ToStatisticTotalCountList(GachaData data, String itemType) in D:\Development\Projects\Snap.Genshin\DGP.Genshin\Service\GachaStatistic\StatisticBuilder.cs:line 189
   at DGP.Genshin.Service.GachaStatistic.StatisticBuilder.ToStatistic(GachaData data, String uid) in D:\Development\Projects\Snap.Genshin\DGP.Genshin\Service\GachaStatistic\StatisticBuilder.cs:line 71
   at DGP.Genshin.Service.GachaStatistic.GachaStatisticService.<>c__DisplayClass7_0.<GetStatisticAsync>b__0() in D:\Development\Projects\Snap.Genshin\DGP.Genshin\Service\GachaStatistic\GachaStatisticService.cs:line 128
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DGP.Genshin.Service.GachaStatistic.GachaStatisticService.GetStatisticAsync(GachaDataCollection gachaData, String uid) in D:\Development\Projects\Snap.Genshin\DGP.Genshin\Service\GachaStatistic\GachaStatisticService.cs:line 128
   at DGP.Genshin.ViewModel.GachaStatisticViewModel.SyncStatisticWithUid() in D:\Development\Projects\Snap.Genshin\DGP.Genshin\ViewModel\GachaStatisticViewModel.cs:line 58
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at DGP.Genshin.App.Main()
```

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Atheris0vv0** [comment]
额 可能是因为我没有更新， 但是我每次点了下载更新之后就没有反应了，再打开就会继续提示我需要更新。
<img width="283" alt="image" src="https://user-images.githubusercontent.com/57121058/171810758-8df94410-67c9-4c14-a1a4-e415a808b91f.png">

**Comment by Atheris0vv0** [comment]
对不起！我重新下载安装了一下就好了！十分抱歉我删不掉这个贴，真的打扰了!
