### ISSUE TITLE
[Bug]: 旧祈愿记录无法读取

### ISSUE THREAD

**Issue by robinbz** [DGP-Studio/Snap.Genshin#309]
### Windows 版本

19043.1706

### Snap Genshin 版本

2022.5.31 build 93

### Snap Genshin 用户设备ID

355ADF6AD7A436FE19B3EEA90604820E

### 发生了什么？

2022年6月3日还能正常看祈愿记录，但6月5日晚上后，旧祈愿记录无法读取，而且保存在本地的记录.json文件无法导入，提示“文件不是UIGF格式，勤支持的UIGF版本较低

### 你期望发生的行为？

希望能读取之前的祈愿记录，并合并新记录

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
json文件提供一下

**Comment by wx98** [comment]
我的也寄了
```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at DGP.Genshin.Service.GachaStatistic.StatisticBuilder.ToStatisticTotalCountList(GachaData data, String itemType) in D:\Development\Projects\Snap.Genshin\DGP.Genshin\Service\GachaStatistic\StatisticBuilder.cs:line 189
   at DGP.Genshin.Service.GachaStatistic.StatisticBuilder.ToStatistic(GachaData data, String uid) in D:\Development\Projects\Snap.Genshin\DGP.Genshin\Service\GachaStatistic\StatisticBuilder.cs:line 71
   at DGP.Genshin.Service.GachaStatistic.GachaStatisticService.<>c__DisplayClass7_0.<GetStatisticAsync>b__0() in D:\Development\Projects\Snap.Genshin\DGP.Genshin\Service\GachaStatistic\GachaStatisticService.cs:line 128
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DGP.Genshin.Service.GachaStatistic.GachaStatisticService.GetStatisticAsync(GachaDataCollection gachaData, String uid) in D:\Development\Projects\Snap.Genshin\DGP.Genshin\Service\GachaStatistic\GachaStatisticService.cs:line 128
   at DGP.Genshin.ViewModel.GachaStatisticViewModel.SyncStatisticWithUid() in D:\Development\Projects\Snap.Genshin\DGP.Genshin\ViewModel\GachaStatisticViewModel.cs:line 58
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at DGP.Genshin.App.Main()
```
![image](https://user-images.githubusercontent.com/33981111/172532541-6e9a4d87-49b7-4f96-93a2-cf9780e31129.png)

**Comment by wx98** [comment]
没事了，我看文档搞好了，（众所周知萌新不会看文档）

**Comment by robinbz** [comment]
[186562935.zip](https://github.com/DGP-Studio/Snap.Genshin/files/8863044/186562935.zip)

**Comment by Lightczx** [comment]
> [186562935.zip](https://github.com/DGP-Studio/Snap.Genshin/files/8863044/186562935.zip)

完全可以正常加载
去设置检查一下元数据

**Comment by robinbz** [comment]
昨天更新版本后才可以正常加载，之前的版本打开就提示导入。不管怎样，更新解决了，谢谢
