### ISSUE TITLE
[Bug]: 无法实现国服与国际服的转换

### ISSUE THREAD

**Issue by starxjys** [DGP-Studio/Snap.Genshin#386]
### Windows 版本

22000.856

### Snap Genshin 版本

2022.8.17 Build11356

### Snap Genshin 用户设备ID

E55C44C468343E8476D3B4672680153B

### 发生了什么？

无法实现国服与国际服的转换
下面是转换时的报错

### 你期望发生的行为？

无法实现国服与国际服的转换

### 相关的崩溃日志

```shell
请稍候已成功识别到游戏路径：D:/Genshin Impact/Genshin Impact Game
当前Pkg最新版本号为：2.8.0-2
YuanShen_Data/app.info .bak 文件不存在，将尝试下一步操作
若无反应请重新下载资源文件！
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/app.info 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/globalgamemanagers 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/globalgamemanagers.assets 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/globalgamemanagers.assets.resS 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/upload_crash.exe 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Managed/Metadata/global-metadata.dat 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Native/Data/Metadata/global-metadata.dat 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Native/UserAssembly.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Native/UserAssembly.exp 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Native/UserAssembly.lib 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/ZFProxyWeb.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/ZFEmbedWeb.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/zf_cef.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/Rewired_DirectInput.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/metakeeper.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/libUbiCustomEvent.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/libGLESv2.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/libEGL.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/chrome_elf.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/cri_mana_vpx.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/cri_vip_unity_pc.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/cri_ware_unity.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/d3dcompiler_47.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/hdiffz.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/hpatchz.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/mihoyonet.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/Mmoron.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/MTBenchmark_Windows.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/NamedPipeClient.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/UnityNativeChromaSDK.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/UnityNativeChromaSDK3.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/Plugins/xlua.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen_Data/StreamingAssets/20527480.blk 备份成功
D:/Genshin Impact/Genshin Impact Game\mhyprot3.Sys 备份成功
D:/Genshin Impact/Genshin Impact Game\mhyprot2.Sys 备份成功
D:/Genshin Impact/Genshin Impact Game\Audio_Chinese_pkg_version 备份成功
D:/Genshin Impact/Genshin Impact Game\pkg_version 备份成功
D:/Genshin Impact/Genshin Impact Game\UnityPlayer.dll 备份成功
D:/Genshin Impact/Genshin Impact Game\YuanShen.exe 备份成功
发生异常：
System.IO.IOException: Access to the path 'D:\Genshin Impact\Genshin Impact Game\YuanShen_Data' is denied.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Genshin.Launcher.Plus.SE.Plugin.ConvertDialogViewModel.ReplaceGameFiles(String[] originalfile, String[] newfile, String scheme) in F:\SG_New\Snap.Genshin\Plugins\Genshin.Launcher.Plus.SE.Plugin\ConvertDialogViewModel.cs:line 433
   at Genshin.Launcher.Plus.SE.Plugin.ConvertDialogViewModel.<>c__DisplayClass41_0.<ConvertGameFileAsync>b__0() in F:\SG_New\Snap.Genshin\Plugins\Genshin.Launcher.Plus.SE.Plugin\ConvertDialogViewModel.cs:line 286
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Genshin.Launcher.Plus.SE.Plugin.ConvertDialogViewModel.ConvertGameFileAsync() in F:\SG_New\Snap.Genshin\Plugins\Genshin.Launcher.Plus.SE.Plugin\ConvertDialogViewModel.cs:line 261
请将该异常反馈给插件作者
```

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
@Dawnfz
