### ISSUE TITLE
[Bug]: 打开成就统计报错

### ISSUE THREAD

**Issue by Undifinedu** [DGP-Studio/Snap.Genshin#410]
### Windows 版本

19043.1889

### Snap Genshin 版本

2022.8.23.5230

### Snap Genshin 用户设备ID

AD98E6EDC8ABF95EC203A211BEBAC8FE

### 发生了什么？

点击成就统计页面后出现报错。无法查看成就

### 你期望发生的行为？

出现成就统计界面，正常查询未完成成就。

### 相关的崩溃日志

```shell
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: $. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Snap.Data.Json.Json.ToObject[T](String value) in D:\Develop\Projects\Snap.Genshin\Common\Snap.Data.Json\Json.cs:line 23
   at Snap.Data.Json.Json.ToObjectOrNew[T](String value) in D:\Develop\Projects\Snap.Genshin\Common\Snap.Data.Json\Json.cs:line 42
   at DGP.Genshin.ViewModel.MetadataViewModel.ProbeCollcetion[T](T& collection, String fileName, Func`2 firstTimeFactory) in D:\Develop\Projects\Snap.Genshin\DGP.Genshin\ViewModel\MetadataViewModel.cs:line 259
   at DGP.Genshin.ViewModel.MetadataViewModel.get_AchievementGoals() in D:\Develop\Projects\Snap.Genshin\DGP.Genshin\ViewModel\MetadataViewModel.cs:line 171
   at DGP.Genshin.ViewModel.AchievementViewModel.OpenUI(Func`2 importer) in D:\Develop\Projects\Snap.Genshin\DGP.Genshin\ViewModel\AchievementViewModel.cs:line 126
   at CommunityToolkit.Mvvm.Input.RelayCommand`1.Execute(Object parameter)
   at DGP.Genshin.Page.AchievementPage.OnNavigatedTo(NavigationEventArgs e) in D:\Develop\Projects\Snap.Genshin\DGP.Genshin\Page\AchievementPage.xaml.cs:line 27
   at ModernWpf.Controls.Page.InternalOnNavigatedTo(NavigationEventArgs e)
   at ModernWpf.Controls.Frame.OnNavigated(Object sender, NavigationEventArgs e)
   at System.Windows.Navigation.NavigationService.FireNavigated(Object navState)
   at System.Windows.Navigation.NavigationService.HandleNavigated(Object navState, Boolean navigatedToNewContent)
   at System.Windows.Navigation.NavigationService.MS.Internal.AppModel.IContentContainer.OnContentReady(ContentType contentType, Object bp, Uri bpu, Object navState)
   at System.Windows.Navigation.NavigationService.DoNavigate(Object bp, NavigationMode navFlags, Object navState)
   at System.Windows.Navigation.NavigateQueueItem.Dispatch(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at DGP.Genshin.App.Main()
```

### Snap Genshin 用户守则及相关的隐私条款

- [X] 我同意遵守 Snap Genshin 用户守则及相关的隐私条款

**Comment by Lightczx** [comment]
更新元数据
