### ISSUE TITLE
查看抽卡数据崩溃

### ISSUE THREAD

**Issue by x0rz4** [DGP-Studio/Snap.Genshin#49]
请将程序根目录下的crash.log(如果有)提交
或者将内容复制后粘贴在下方的6个 \` 之内
```
Snap Genshin - 2021.10.31.10000
System.NotSupportedException: 未找到适用于完成此操作的图像处理组件。
 ---> System.Runtime.InteropServices.COMException (0x88982F50): 无法找不到组件。 (0x88982F50)
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at DGP.Genshin.Controls.Infrastructures.CachedImage.ImageAsyncHelper.<>c.<<-cctor>b__7_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at DGP.Genshin.App.Main()

```

> 在下方详细描述您遇到的问题
查看抽卡数据崩溃

**Comment by Lightczx** [comment]
在`Cache`文件夹里面找一下有没有裂图（加载不出来缩略图的文件），删掉，重新打开程序重新校验完整性即可

**Comment by x0rz4** [comment]
老哥我建议还是把图片保存在更新里面，然后Releases虽然大一点但是这样速度快很多启动直接就使用就可以了不用再加载图片，有时候图片加载不来卡住真的烦

**Comment by x0rz4** [comment]
可以做两个版本，一个完整版一个精简版，其实也有很多科学上网党的，两个版本应该可以完美解决

**Comment by x0rz4** [comment]
就算是更新放在国内也一样卡住不动[![https://www.hualigs.cn/image/61813f1f89872.jpg](https://www.hualigs.cn/image/61813f1f89872.jpg)](https://www.hualigs.cn/image/61813f1f89872.jpg)

**Comment by Lightczx** [comment]
https://github.com/DGP-Studio/DGP.Genshin.Cache/releases/tag/2021.10.30.10000

**Comment by Lightczx** [comment]
图片用的是Honey的资源
