### ISSUE TITLE
2021.12.9 build36版本启动游戏功能会卡死

### ISSUE THREAD

**Issue by BeiChenPorarisu** [DGP-Studio/Snap.Genshin#83]

**Comment by BeiChenPorarisu** [comment]
crash日志文件中的内容如下
Snap Genshin - 2021.12.9.36
IniParser.Exceptions.ParsingException: Duplicate section with name 'General' on line '[General]' while parsing line number 0 with value '' - IniParser version: 2.5.2.0 while parsing line number 7 with value '[General]' - IniParser version: 2.5.2.0
 ---> IniParser.Exceptions.ParsingException: Duplicate section with name 'General' on line '[General]' while parsing line number 0 with value '' - IniParser version: 2.5.2.0
   at IniParser.Parser.IniDataParser.ProcessSection(String line, IniData currentIniData)
   at IniParser.Parser.IniDataParser.ProcessLine(String currentLine, IniData currentIniData)
   at IniParser.Parser.IniDataParser.Parse(String iniDataString)
   --- End of inner exception stack trace ---
   at IniParser.Parser.IniDataParser.Parse(String iniDataString)
   at IniParser.StreamIniDataParser.ReadData(StreamReader reader)
   at IniParser.FileIniDataParser.ReadFile(String filePath, Encoding fileEncoding)
   at IniParser.FileIniDataParser.ReadFile(String filePath)
   at DGP.Genshin.Services.Launching.LaunchService..ctor() in D:\Development\Projects\Snap.Genshin\DGP.Genshin\Services\Launching\LaunchService.cs:line 221
   at DGP.Genshin.Services.Launching.LaunchService.get_Instance() in D:\Development\Projects\Snap.Genshin\DGP.Genshin\Services\Launching\LaunchService.cs:line 234
   at DGP.Genshin.Controls.TitleBarButtons.LaunchTitleBarButton.LaunchTitleBarButtonClick(Object sender, RoutedEventArgs e) in D:\Development\Projects\Snap.Genshin\DGP.Genshin\Controls\TitleBarButtons\LaunchTitleBarButton.xaml.cs:line 70
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at DGP.Genshin.App.Main()

**Comment by Lightczx** [comment]
是不是有别的启动器启动过

**Comment by BeiChenPorarisu** [comment]
https://github.com/DawnFz/GenShin-LauncherDIY
用过这个

**Comment by Lightczx** [comment]
@DawnFz 怎么回事，是不是代码写歪了

**Comment by Lightczx** [comment]
> https://github.com/DawnFz/GenShin-LauncherDIY 用过这个

还请提供一下现在的原神 config.ini 文件的内容

**Comment by BeiChenPorarisu** [comment]
[launcher]
cps=mihoyo
channel=1
sub_channel=1
game_install_path=D:/Games/Genshin Impact/Genshin Impact Game
game_dynamic_bg_name=8116f8be40703077a654194f0224cbe8_5291806154613456826.png
game_dynamic_bg_md5=215c2c87ae7e8d8b11873f3a049ad057
game_start_name=YuanShen.exe
exit_type=1
speed_limit_enabled=false
is_first_exit=false

**Comment by Lightczx** [comment]
不不，不是这个，yuanshen.exe 旁边的ini

**Comment by BeiChenPorarisu** [comment]
[General]
channel=1
cps=pcadbdpz
game_version=2.3.0
sub_channel=1
sdk_version=
[General]
sub_channel=1
channel=1
cps=pcadbdpz

**Comment by DawnFz** [comment]
我试了并不会新创建一个节出来啊🥲

**Comment by Lightczx** [comment]
> [General] channel=1 cps=pcadbdpz game_version=2.3.0 sub_channel=1 sdk_version= [General] sub_channel=1 channel=1 cps=pcadbdpz

试试把后面的[General] 节整个删掉吧

**Comment by BeiChenPorarisu** [comment]
可以了，但用 @DawnFz 的启动器（1.1.6.0）启动之后那一节又出现了。。
