### ISSUE TITLE
2021.12.19.32版本crash

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Genshin#91]
![WTJKNWEZ%54 D URVK5HFII](https://user-images.githubusercontent.com/10614984/146690812-944e67fa-b18d-4a69-accf-11548e60c409.png)
点击“前往Github反馈”后会直接闪退，日志下附
[2021-12-19 13-07-25-crash.log](https://github.com/DGP-Studio/Snap.Genshin/files/7741605/2021-12-19.13-07-25-crash.log)

**Comment by icimence** [comment]
盲猜游戏路径变了，或者卸载了，导致读不到配置文件

**Comment by Masterain98** [comment]
> 

更新前并没有改过游戏设置，使用的是程序的自动更新，更新前仍然成功加载程序的

**Comment by Masterain98** [comment]
> 盲猜游戏路径变了，或者卸载了，导致读不到配置文件

更新前并没有改过游戏设置，使用的是程序的自动更新，更新前仍然成功加载程序的

**Comment by Lightczx** [comment]
之前有没有打开过 启动游戏 标题栏按钮？@Masterain88

**Comment by Masterain98** [comment]
> 之前有没有打开过 启动游戏 标题栏按钮

把`settings.json`中的`LauncherPath`改为空值后错误变了，并且不生成crash log

```
IniParser.Exceptions.ParsingException: Could not parse file \config.ini while parsing line number 0 with value '' - IniParser version: 2.5.2.0
 ---> System.IO.FileNotFoundException: Could not find file 'C:\config.ini'.
File name: 'C:\config.ini'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at IniParser.FileIniDataParser.ReadFile(String filePath, Encoding fileEncoding)
   --- End of inner exception stack trace ---
   at IniParser.FileIniDataParser.ReadFile(String filePath, Encoding fileEncoding)
   at IniParser.FileIniDataParser.ReadFile(String filePath)
   at DGP.Genshin.Services.Launching.LaunchService.GetIniData(String file) in D:\Development\Projects\Snap.Genshin\DGP.Genshin\Services\Launching\LaunchService.cs:line 86
   at DGP.Genshin.Services.Launching.LaunchService.LoadIniData(String launcherPath) in D:\Development\Projects\Snap.Genshin\DGP.Genshin\Services\Launching\LaunchService.cs:line 64
   at DGP.Genshin.Services.Launching.LaunchService..ctor(ISettingService settingService) in D:\Development\Projects\Snap.Genshin\DGP.Genshin\Services\Launching\LaunchService.cs:line 54
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at DGP.Genshin.App.GetService[TService]() in D:\Development\Projects\Snap.Genshin\DGP.Genshin\App.xaml.cs:line 56
   at DGP.Genshin.App.GetViewModel[TViewModel]() in D:\Development\Projects\Snap.Genshin\DGP.Genshin\App.xaml.cs:line 67
   at DGP.Genshin.Controls.TitleBarButtons.LaunchTitleBarButton..ctor() in D:\Development\Projects\Snap.Genshin\DGP.Genshin\Controls\TitleBarButtons\LaunchTitleBarButton.xaml.cs:line 13
   at DGP.Genshin.MainWindow.PrepareTitleBarArea(SplashViewModel splashView) in D:\Development\Projects\Snap.Genshin\DGP.Genshin\MainWindow.xaml.cs:line 70
   at DGP.Genshin.MainWindow.Receive(SplashInitializationCompletedMessage message) in D:\Development\Projects\Snap.Genshin\DGP.Genshin\MainWindow.xaml.cs:line 48
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at DGP.Genshin.App.Main()
```

**Comment by Lightczx** [comment]
你需要把整个字段删除，而不是置空

**Comment by Masterain98** [comment]
> 你需要把整个字段删除，而不是置空

fixed

**Comment by Lightczx** [comment]
应该是你的 F:\Genshin Impact\ 下没有 config.ini
